#include "sgdlib/data/dataset_manager.hpp"
#include "sgdlib/algorithm/cd/scd.hpp"
#include "sgdlib/algorithm/gd/sgd.hpp"
#include "sgdlib/algorithm/gd/sag.hpp"
#include "sgdlib/algorithm/lbfgs/lbfgs.hpp"
